'use client';

import { useState } from 'react';
import { trpc } from '@/lib/trpc';

export default function AdminSystemPage() {
  const utils = trpc.useUtils();
  const { data: embeddingsStatus, isLoading } = trpc.admin.embeddingsStatus.useQuery();
  const backfill = trpc.admin.backfillEmbeddings.useMutation({
    onSuccess: () => utils.admin.embeddingsStatus.invalidate(),
  });
  const [force, setForce] = useState(false);

  const coverage =
    embeddingsStatus && embeddingsStatus.total > 0
      ? Math.round((embeddingsStatus.withEmbedding / embeddingsStatus.total) * 100)
      : 0;

  return (
    <div className="max-w-4xl">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold">System</h1>
        <p className="text-sm text-ink-500 dark:text-ink-400 mt-1">
          System-level health and infrastructure controls.
        </p>
      </header>

      <section className="bg-white dark:bg-ink-900 border border-ink-200 dark:border-ink-800 rounded-lg p-5">
        <div className="flex items-start justify-between gap-4 mb-4">
          <div>
            <h2 className="font-medium">Semantic embeddings</h2>
            <p className="text-sm text-ink-500 dark:text-ink-400 mt-1">
              Vector embeddings power the &quot;similar matters&quot; context card and
              future semantic archive search. Generated by the worker on each
              new matter and stored in <code className="text-xs">matters.embedding</code>.
            </p>
          </div>
        </div>

        {isLoading ? (
          <div className="text-sm text-ink-500 dark:text-ink-400">Loading…</div>
        ) : embeddingsStatus ? (
          <>
            <div className="space-y-2 mb-4">
              <div className="flex items-baseline justify-between gap-4">
                <span className="text-sm text-ink-600 dark:text-ink-400">Coverage</span>
                <span className="text-lg font-semibold tabular-nums">
                  {embeddingsStatus.withEmbedding}/{embeddingsStatus.total}
                  <span className="ml-2 text-sm font-normal text-ink-500 dark:text-ink-400">
                    ({coverage}%)
                  </span>
                </span>
              </div>
              <div className="h-2 bg-ink-100 dark:bg-ink-800 rounded-full overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-brand-500 to-brand-600 transition-all"
                  style={{ width: `${coverage}%` }}
                />
              </div>
              {embeddingsStatus.withoutEmbedding > 0 && (
                <p className="text-xs text-amber-600 dark:text-amber-400 mt-2">
                  {embeddingsStatus.withoutEmbedding} matter{embeddingsStatus.withoutEmbedding === 1 ? '' : 's'}{' '}
                  without embeddings — likely missing because <code>OPENAI_API_KEY</code> was
                  unset when they were triaged. Backfill below to enqueue regeneration.
                </p>
              )}
            </div>

            <div className="flex items-center gap-3 mt-4 pt-4 border-t border-ink-100 dark:border-ink-800">
              <label className="flex items-center gap-2 text-xs text-ink-600 dark:text-ink-400">
                <input
                  type="checkbox"
                  checked={force}
                  onChange={(e) => setForce(e.target.checked)}
                  className="rounded border-ink-300 dark:border-ink-700"
                />
                Force re-embed all matters (not just NULL)
              </label>
              <button
                onClick={() => backfill.mutate({ force })}
                disabled={backfill.isPending}
                className="ml-auto text-sm border rounded px-3 py-1.5 hover:bg-ink-50 dark:hover:bg-ink-800 disabled:opacity-50"
              >
                {backfill.isPending
                  ? 'Enqueuing…'
                  : force
                    ? 'Re-embed all matters'
                    : 'Backfill missing embeddings'}
              </button>
            </div>
            {backfill.data && (
              <p className="text-xs text-emerald-600 dark:text-emerald-400 mt-3">
                Enqueued {backfill.data.enqueued} generate_embedding job
                {backfill.data.enqueued === 1 ? '' : 's'}. Worker will process them as it polls.
              </p>
            )}
            {backfill.error && (
              <p className="text-xs text-red-600 dark:text-red-400 mt-3">
                {backfill.error.message}
              </p>
            )}
          </>
        ) : null}
      </section>
    </div>
  );
}
